name=r2common
version=0.0.1
author=TordWessman
maintainer=TordWessman
sentence=Common C++ utilities for Arduino microcontrollers
paragraph=HTTP networking and Result types
category=Communication
url=https://github.com/TordWessman/r2common
architectures=*
