[env]
framework = arduino
monitor_speed = 9600
lib_deps =
    symlink://../../
    symlink:///Users/olga/Dropbox/workspace_dropbox/Arduino/r2common/lib/r2common

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
